const FLAGS: Record<string, string> = {
  // LATAM
  Argentina: '🇦🇷',
  Brazil: '🇧🇷',
  Colombia: '🇨🇴',
  Uruguay: '🇺🇾',
  Ecuador: '🇪🇨',
  Paraguay: '🇵🇾',
  // Resto de grupos — usados en bracket/stats
  Mexico: '🇲🇽',
  'United States': '🇺🇸',
  USA: '🇺🇸',
  Canada: '🇨🇦',
  Spain: '🇪🇸',
  France: '🇫🇷',
  Germany: '🇩🇪',
  England: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  Portugal: '🇵🇹',
  Netherlands: '🇳🇱',
  Italy: '🇮🇹',
  Belgium: '🇧🇪',
  Croatia: '🇭🇷',
  Morocco: '🇲🇦',
  Senegal: '🇸🇳',
  Japan: '🇯🇵',
  'South Korea': '🇰🇷',
  Australia: '🇦🇺',
  'Saudi Arabia': '🇸🇦',
  Iran: '🇮🇷',
  Tunisia: '🇹🇳',
  Nigeria: '🇳🇬',
  'Ivory Coast': '🇨🇮',
  Cameroon: '🇨🇲',
  'South Africa': '🇿🇦',
  Egypt: '🇪🇬',
  Algeria: '🇩🇿',
  Ghana: '🇬🇭',
  Switzerland: '🇨🇭',
  Poland: '🇵🇱',
  Ukraine: '🇺🇦',
  Denmark: '🇩🇰',
  Sweden: '🇸🇪',
  Austria: '🇦🇹',
  Turkey: '🇹🇷',
  Serbia: '🇷🇸',
  Romania: '🇷🇴',
  Hungary: '🇭🇺',
  Slovakia: '🇸🇰',
  'Czech Republic': '🇨🇿',
  Czechia: '🇨🇿',
  Slovenia: '🇸🇮',
  Albania: '🇦🇱',
  Georgia: '🇬🇪',
  Iraq: '🇮🇶',
  Jordan: '🇯🇴',
  Qatar: '🇶🇦',
  Uzbekistan: '🇺🇿',
  Indonesia: '🇮🇩',
  Philippines: '🇵🇭',
  Thailand: '🇹🇭',
  Vietnam: '🇻🇳',
  'New Zealand': '🇳🇿',
  Panama: '🇵🇦',
  Honduras: '🇭🇳',
  'Costa Rica': '🇨🇷',
  Cuba: '🇨🇺',
  Jamaica: '🇯🇲',
  'Trinidad and Tobago': '🇹🇹',
  Curacao: '🇨🇼',
  'Curaçao': '🇨🇼',
  Venezuela: '🇻🇪',
  Chile: '🇨🇱',
  Bolivia: '🇧🇴',
  'DR Congo': '🇨🇩',
  'Cape Verde': '🇨🇻',
  Libya: '🇱🇾',
  Guinea: '🇬🇳',
  Mozambique: '🇲🇿',
  Tanzania: '🇹🇿',
  Angola: '🇦🇴',
  Benin: '🇧🇯',
  Kuwait: '🇰🇼',
  Bahrain: '🇧🇭',
  Oman: '🇴🇲',
  UAE: '🇦🇪',
  Israel: '🇮🇱',
  Greece: '🇬🇷',
  Scotland: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  Wales: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Northern Ireland': '🇬🇧',
}

export function getFlag(team: string): string {
  return FLAGS[team] ?? '🏳️'
}

export const LATAM_TEAMS = ['Argentina', 'Brazil', 'Colombia', 'Uruguay', 'Ecuador', 'Paraguay']
export const LATAM_GROUPS: Record<string, string> = {
  Argentina: 'J',
  Brazil: 'C',
  Colombia: 'K',
  Uruguay: 'H',
  Ecuador: 'E',
  Paraguay: 'D',
}
